
# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  # ps: Bootstrap
  # Install maven and dependencies
  - ps: .\dev\appveyor-install-dependencies.ps1
  # Required package for R unit tests
  - cmd: R -e "install.packages(c('methods', 'KEGGgraph', 'biomaRt', 'bigmemory', 'sqldf','CompQuadForm','data.table','lattice','igraph'), repos='http://cran.us.r-project.org')"
  - cmd: R -e "packageVersion('methods'); packageVersion('KEGGgraph'); packageVersion('tbiomaRt'); packageVersion('bigmemory'); packageVersion('sqldf'); packageVersion('CompQuadForm'); packageVersion('data.table'); packageVersion('lattice'); packageVersion('igraph')"

environment:
  global:
   WARNINGS_ARE_ERRORS: 0
   USE_RTOOLS: true

build_script:
  - R -e  "0" --args --bootstrap-packrat

test_script:
  - travis-tool.sh run_tests

cache:
  - packages -> appveyor.yml    # or any other file
